############ CRUCIAL SETTINGS ############
firstTimeSetup: 0 # First day Plugin setup in this server, don't change this section if you don't know what you are doing
checkDayPeriod: 30 # Day check period in this server(in seconds), lower value is more accurate but may cause lag
############ WORLD SETTINGS ############
worldDaySettings:
  world: 24000
  # <world_name>: <ticks_per_day_in_world> # <world_name> is the name of the world, <ticks_per_day_in_world> is the ticks per day in that world
  #world_nether: 24000 # not use default because nether don't have day cycle
############ HP SETTINGS ############
hp: # HP settings
  start: 20 # Starting HP for players
  maxHP: # Max HP player
    enabled: false # Enable max HP limit (true/false), when true, player has max HP limit
    amount: 140 # Amount of Max HP limit for players
    dropHealthItem: true # Drop health item when player reach max HP when dead increase
  minHP: # Min HP player
    enabled: false # (true/false) when true, player has min HP limit, when false, player with 0 HP getting ban
    amount: 2 # Amount of Min HP player limit
    banTime: 24 # Ban time in real life hours, set to 0 to ban permanently
  afterBan: 2 # Health after player get ban and return back to server after ban
############ HEALTH ITEM SETTINGS ############
healthItem:
  material: "NETHER_STAR"  # Material item
  name: "&cHealth Token"  # Item Name
  lore:  # Item Description
    - "&7Right click to use"
    - ""
    - "&7Can be used to Increase your &7Max Health"
  healthPerItem: 2  # Health per item
  cannotToCraft: ["BEACON"] # List of items that cannot be crafted using health item

############ PRIORITY DEATH SETTINGS ############
priority: ["IGNORE", "INCREASE", "DECREASE"]
# Priority death, checking player die with higher priority first, when player die with that type, it will not check other type
# List of death type: IGNORE, INCREASE, DECREASE
############ IGNORE DEATH SETTINGS ############
ignore: # Ignore death
  enabled: false # (true/false) when true, player can ignore their death
  must_difference: false # (true/false) when true, player who had died with ignore cause before, cannot used ignore with same cause again
  # when false, player always ignore HP with ignore cause, even repeat death with same cause type, did not record their death data
  cause: # Ignored death type
    - ALL # Ignore all death type
    #- LAVA
    #- FALL
    #- etc
  day: # Ignored day settings
    enabled: false # true or false, when true, ignored day is active
    must_difference: false # (true/false) when true, player who had died with ignore day cause before, cannot ignore with same day cause again
    # when false, player always ignore HP with ignore day cause, even repeat death with same day cause type, did not record their death data
    deActiveIncrease: false # true or false, when true, increase death not active when ignore day
    deActiveDecrease: false # true or false, when true, decrease death not active when ignore day
    deActiveIncreaseDay: false # true or false, when true, increase day not active when ignore day
    deActiveDecreaseDay: false # true or false, when true, decrease day not active when ignore day
    type: "minecraft" # "real" for real-world days, "minecraft" for minecraft days
    days: [ 19, 23, 29 ] # List of days (as multiples) when ignored day is active
    cause: # Ignored day cause (death type)
      - ALL # Ignore all death type
      #- LAVA
      #- FALL
      #- etc
############ INCREASE DEATH SETTINGS ############
increase: # Increase HP player when they die
  enabled: true # true or false, when true, player can increase their HP
  must_difference: true # (true/false) when true, player who had died with increase cause before, cannot used increase with same cause again
  # when false, player always increase HP with increase cause, even repeat death with same cause type, did not record their death data
  cause: # Increase death type and Increase amount, (TYPE::AMOUNT)
    - ALL::2 # Increase all death type
    #- LAVA::4
    - FALL::1 # If using ALL but need custom increase amount for some death type, you can add below like this
    # - etc
  day: # Increase day settings
    enabled: false # true or false, when true, increase day is active
    must_difference: true # (true/false) when true, player who had died with increase day cause before, cannot increase with same day cause again
    # when false, player always increase HP with increase day cause, even repeat death with same day cause type, did not record their death data
    deActiveIgnore: false # true or false, when true, ignore death not active when increase day
    deActiveDecrease: false # true or false, when true, decrease death not active when increase day
    deActiveIgnoreDay: false # true or false, when true, ignore day not active when increase day is active
    deActiveDecreaseDay: false # true or false, when true, decrease day not active when increase day is active
    type: "minecraft" # "real" for real-world days, "minecraft" for minecraft days
    days: [ 11, 13, 17 ] # List of days (as multiples) when increase day is active
    cause: # Increase day cause (death type and increase amount), (TYPE::AMOUNT)
      - ALL::10 # Increase all death type
      - LAVA::14 # If using ALL but need custom increase day amount for some death type, you can add below like this
      #- FALL::4
      # - etc
############ DECREASE DEATH SETTINGS ############
decrease: #decrease HP player when death with certain type
  enabled: false # true or false, when true, player can decrease their HP
  must_difference: false # (true/false) when true, player who had died with decrease cause before, cannot decrease with same cause again
  # when false, player always decrease HP with decrease cause, even repeat death with same cause type, did not record their death data
  debt: true # (true/false) when true, player when got decrease but don't have enough HP, when they increase HP their HP will use to pay debt
  cause: # Decrease death type and Decrease amount, (TYPE::AMOUNT)
    - ALL::4 # Decrease all death type
    - PLAYER_ATTACK::6 # If using ALL but need custom decrease amount for some death type, you can add below like this
    #- FALL::10
    #- etc
  day: # Decrease day settings
    enabled: false # true or false, when true, decrease day is active
    must_difference: false # (true/false) when true, player who had died with decrease day cause before, cannot decrease with same day cause again
    # when false, player always decrease HP with decrease day cause, even repeat death with same day cause type, did not record their death data
    deActiveIgnore: false # true or false, when true, ignore death not active when decrease day
    deActiveIncrease: false # true or false, when true, increase death not active when decrease day
    deActiveIgnoreDay: false # true or false, when true, ignore day not active when decrease day is active
    deActiveIncreaseDay: false # true or false, when true, increase day not active when decrease day is active
    type: "minecraft" # "real" for real-world days, "minecraft" for minecraft days
    days: [ 5, 7 ] # List of days (as multiples) when decrease day is active
    cause: # Decrease day cause (death type and decrease amount), (TYPE::AMOUNT)
      - ALL::16 # Decrease all death type
      - PLAYER_ATTACK::18 # If using ALL but need custom decrease day amount for some death type, you can add below like this
      #- FALL::20
      #- etc

############ SEASON SETTINGS ############
season: # Season settings, add season days to death data player, so player can death with same cause again when season change
  enabled: true # true or false, when true, season is active
  type: "real" # "real" for real-world day per season, "minecraft" for minecraft day per season
  day: 30 # day (as multiples) when season is change
  resetWorldDay: false # true or false, when true, reset all world day and irl world setting day back to 0 when season is change
############ PERMISSION SETTINGS ############
permissionsAllPlayer: # Give permission to all player, OP can use command without permission
  reload: false # allow reload command to all player
  setConfig: false # allow setConfig command to all player
  setMaxHealth: false # allow setMaxHealth command to all player
  viewHealth: false # allow viewHealth command to all player
  viewDeathData: true # allow viewDeathData command to all player
  viewDebtData: true # allow viewDebtData command to all player
  resetHealth: false # allow resetHealth command to all player
  matchHealth: false # allow matchHealth command to all player
  removeDeathData: false # allow removeDeathData command to all player
  removeDebtData: false # allow removeDebtData command to all player
  transferHealth: true # allow transferHealth command to all player
  withdrawHealth: true # allow withdrawHealth command to all player
  help: true # allow help command to all player
############ NOTIFICATION SETTINGS ############
notifications:
  defaultDeathMessage: false # true or false, when false, another player won't receive default death message
  player:
    maxHealth: "&bYou&f have reached the&c maximum health limit&f."
    minHealth: "&bYou&f have reached the&c minimum health limit&f."
    banReason: "&bYou&f have been&c banned&f due to low health"
    kicked: "&bYou&f have been&c kicked&f due to low health"

    ignored: "&fDied with &c{cause}&f now&c not increased&f HP"
    ignoredSameWay: "&cCan't&f ignoring again cause&c you died&f with&c same way"

    increased: "&bYou&a increased &d{increase}&f health cause: &c{cause}"
    increaseSameWay: "&bYou&c don't increased health&f with death same way"

    decreased: "&bYou&c decrease &d{decrease}&f health cause: &c{cause}"
    decreaseSameWay: "&bYou&c don't decreased health&f with death same way"

    debtPaidOff: "&bYou&f have paid off&c {debtPaid}&f health debt"
    debtReduced: "&bYou&f have reduced&c {debtPaid}&f health debt, now&c {debtLeft}&f health debt left"
    debtAdded: "&bYou&f have added&c {debtAdded}&f health debt, now&c {debtLeft}&f health debt you must pay"
    
    # Warning messages for special days
    warning:
      ignoredDay: "&6⚠ &eToday is an &6Ignored Day&e! Deaths won't affect your HP!"
      increaseDay: "&6⚠ &eToday is an &aIncrease Day&e! Get extra HP on death!"
      decreaseDay: "&6⚠ &eToday is a &cDecrease Day&e! Be careful, you'll lose more HP on death!"
      seasonChange: "&6⚠ &eSeason changed! Reset your death data!"

  logServer:
    maxHealth: "&b{name}&f have reached the&c maximum health limit&f."
    minHealth: "&b{name}&f have reached the&c minimum health limit&f."

    increased: "&b{name}&a increase&d {increase}&f health by&b {cause}"
    decreased: "&b{name}&c decrease&d {decrease}&f health cause:&c {cause}"
    banReason: "&b{name}&f has been&c banned&f due to low health"