# config.yml
HP:
  start: 20 #Sart HP player
  gained:
    per_death: 2 #HP Gained per player death
    max:
      enabled: false #Max HP player, true or false, when true, player has max HP limit
      amount: 114 #Max HP player limit
  decrease: #decrease HP player when death with certain type
    enabled: false #true or false, when true, player can decrease their HP
    per_death: 2 #HP decrease per player death
    min: #HP minimum player when always death with decrease type
      enabled: false #true or false, when true, player has min HP limit
      amount: 2 #Min HP player limit

death:
  must_difference: true #true or false, when true, player must die with different way to gained HP
  ignored: #Ignored death type cause player not gain HP
  #  - lava
  #  - fall
  decrease: #decrease HP player when death with certain type
  #  - lava
  #  - fall

notifications:
  death_message:
    player:
      gained: "&fYou gained &9{gain}&f health cause : &c{cause}"
      ifSameWay: "&cYou don't gained health with death same way"
      ignored: "&fDied with &c{cause}&f not gained HP"
      decrease: "&fYou decrease &c{decrease}&f health cause : &c{cause}"
      maxHealth: "&fYou have reached the&c maximum health limit&f."
    logServer:
      gained: "{name} gained {gain} health by {cause}"
      decrease: "{name} decrease {decrease} health cause : {cause}"
